version: "3.9"

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: mcg_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mcg_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: mcg_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcg_user -d mcg_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4-alpine
    container_name: mcg_redis
    restart: unless-stopped
    command: >
      redis-server
        --requirepass ${REDIS_PASSWORD:?err}
        --appendonly yes
        --maxmemory 256mb
        --maxmemory-policy allkeys-lru
        --tls-port 6379
        --port 0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
